# Generated by Django 6.0.2 on 2026-03-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('wooden', 'Wooden'), ('clothes', 'Clothes')], default='null', max_length=50),
        ),
    ]
