# Generated by Django 6.0.2 on 2026-03-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('others', 'Ohers'), ('clothes', 'Clothes')], default='null', max_length=50),
        ),
    ]
