# Generated by Django 6.0.2 on 2026-04-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('wooden', 'Wooden'), ('clothes', 'Clothes')], max_length=50),
        ),
    ]
